"""Add API Key Model

Revision ID: 192d40d774cc
Revises: ab7eb1b383ee
Create Date: 2025-03-04 18:33:35.969062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192d40d774cc'
down_revision: Union[str, None] = 'ab7eb1b383ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
