"""contract inv

Revision ID: 1fcaa5cb18ee
Revises: a006c54eeca0
Create Date: 2025-03-05 17:26:14.184717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcaa5cb18ee'
down_revision: Union[str, None] = 'a006c54eeca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='invitationstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_contract_invitations_id'), 'contract_invitations', ['id'], unique=False, schema='esign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esign_contract_invitations_id'), table_name='contract_invitations', schema='esign')
    op.drop_table('contract_invitations', schema='esign')
    # ### end Alembic commands ###
