"""contract

Revision ID: 5303c8464070
Revises: 66258311652f
Create Date: 2025-03-05 17:08:03.280691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5303c8464070'
down_revision: Union[str, None] = '66258311652f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_name', sa.String(), nullable=False),
    sa.Column('freelancer_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('freelancer_signature_id', sa.UUID(), nullable=True),
    sa.Column('company_signature_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_signature_id'], ['esign.signatures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['freelancer_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['freelancer_signature_id'], ['esign.signatures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_contracts_id'), 'contracts', ['id'], unique=False, schema='esign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esign_contracts_id'), table_name='contracts', schema='esign')
    op.drop_table('contracts', schema='esign')
    # ### end Alembic commands ###
