"""fix salt bruh

Revision ID: 66258311652f
Revises: a9f4e0bbccc1
Create Date: 2025-03-05 12:41:54.128450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66258311652f'
down_revision: Union[str, None] = 'a9f4e0bbccc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encryption_key_hash', schema='esign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encryption_key_hash', sa.VARCHAR(), autoincrement=False, nullable=True), schema='esign')
    # ### end Alembic commands ###
