"""Add API logging tables

Revision ID: 78ebf290641f
Revises: 1b7a65264228
Create Date: 2025-03-04 14:44:06.016657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78ebf290641f'
down_revision: Union[str, None] = '1b7a65264228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='api_management'
    )
    op.create_index(op.f('ix_api_management_api_keys_api_key'), 'api_keys', ['api_key'], unique=True, schema='api_management')
    op.create_index(op.f('ix_api_management_api_keys_id'), 'api_keys', ['id'], unique=False, schema='api_management')
    op.create_table('api_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_management.api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='api_management'
    )
    op.create_index(op.f('ix_api_management_api_logs_id'), 'api_logs', ['id'], unique=False, schema='api_management')
    op.create_table('api_usage_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year_week', sa.String(), nullable=False),
    sa.Column('year_month', sa.String(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('usage_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_management.api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='api_management'
    )
    op.create_index(op.f('ix_api_management_api_usage_summary_date'), 'api_usage_summary', ['date'], unique=False, schema='api_management')
    op.create_index(op.f('ix_api_management_api_usage_summary_id'), 'api_usage_summary', ['id'], unique=False, schema='api_management')
    op.create_index(op.f('ix_api_management_api_usage_summary_year_month'), 'api_usage_summary', ['year_month'], unique=False, schema='api_management')
    op.create_index(op.f('ix_api_management_api_usage_summary_year_week'), 'api_usage_summary', ['year_week'], unique=False, schema='api_management')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_management_api_usage_summary_year_week'), table_name='api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_usage_summary_year_month'), table_name='api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_usage_summary_id'), table_name='api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_usage_summary_date'), table_name='api_usage_summary', schema='api_management')
    op.drop_table('api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_logs_id'), table_name='api_logs', schema='api_management')
    op.drop_table('api_logs', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_keys_id'), table_name='api_keys', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_keys_api_key'), table_name='api_keys', schema='api_management')
    op.drop_table('api_keys', schema='api_management')
    # ### end Alembic commands ###
