"""contract inv 2

Revision ID: 937cea7f4d41
Revises: 1fcaa5cb18ee
Create Date: 2025-03-06 12:35:52.069978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937cea7f4d41'
down_revision: Union[str, None] = '1fcaa5cb18ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
