"""contract 2

Revision ID: a006c54eeca0
Revises: 5303c8464070
Create Date: 2025-03-05 17:15:39.726091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a006c54eeca0'
down_revision: Union[str, None] = '5303c8464070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signature_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['esign.contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signature_id'], ['esign.signatures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_contract_parties_id'), 'contract_parties', ['id'], unique=False, schema='esign')
    op.drop_constraint('contracts_freelancer_signature_id_fkey', 'contracts', schema='esign', type_='foreignkey')
    op.drop_constraint('contracts_freelancer_id_fkey', 'contracts', schema='esign', type_='foreignkey')
    op.drop_constraint('contracts_company_signature_id_fkey', 'contracts', schema='esign', type_='foreignkey')
    op.drop_constraint('contracts_company_id_fkey', 'contracts', schema='esign', type_='foreignkey')
    op.drop_column('contracts', 'company_signature_id', schema='esign')
    op.drop_column('contracts', 'freelancer_id', schema='esign')
    op.drop_column('contracts', 'freelancer_signature_id', schema='esign')
    op.drop_column('contracts', 'company_id', schema='esign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False), schema='esign')
    op.add_column('contracts', sa.Column('freelancer_signature_id', sa.UUID(), autoincrement=False, nullable=True), schema='esign')
    op.add_column('contracts', sa.Column('freelancer_id', sa.UUID(), autoincrement=False, nullable=False), schema='esign')
    op.add_column('contracts', sa.Column('company_signature_id', sa.UUID(), autoincrement=False, nullable=True), schema='esign')
    op.create_foreign_key('contracts_company_id_fkey', 'contracts', 'users', ['company_id'], ['id'], source_schema='esign', referent_schema='esign', ondelete='CASCADE')
    op.create_foreign_key('contracts_company_signature_id_fkey', 'contracts', 'signatures', ['company_signature_id'], ['id'], source_schema='esign', referent_schema='esign', ondelete='SET NULL')
    op.create_foreign_key('contracts_freelancer_id_fkey', 'contracts', 'users', ['freelancer_id'], ['id'], source_schema='esign', referent_schema='esign', ondelete='CASCADE')
    op.create_foreign_key('contracts_freelancer_signature_id_fkey', 'contracts', 'signatures', ['freelancer_signature_id'], ['id'], source_schema='esign', referent_schema='esign', ondelete='SET NULL')
    op.drop_index(op.f('ix_esign_contract_parties_id'), table_name='contract_parties', schema='esign')
    op.drop_table('contract_parties', schema='esign')
    # ### end Alembic commands ###
