"""Hashed Password Key Salt

Revision ID: a9f4e0bbccc1
Revises: dea18c0f6c17
Create Date: 2025-03-05 12:31:02.624279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f4e0bbccc1'
down_revision: Union[str, None] = 'dea18c0f6c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encryption_salt', sa.LargeBinary(), nullable=True), schema='esign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encryption_salt', schema='esign')
    # ### end Alembic commands ###
