"""Added full name, phone, and UUID to User model

Revision ID: c7877ea82860
Revises: 
Create Date: 2025-03-03 15:59:21.911797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7877ea82860'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_users_email'), 'users', ['email'], unique=True, schema='esign')
    op.create_index(op.f('ix_esign_users_id'), 'users', ['id'], unique=False, schema='esign')
    op.create_table('keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('private_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_keys_id'), 'keys', ['id'], unique=False, schema='esign')
    op.create_table('signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_signatures_id'), 'signatures', ['id'], unique=False, schema='esign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esign_signatures_id'), table_name='signatures', schema='esign')
    op.drop_table('signatures', schema='esign')
    op.drop_index(op.f('ix_esign_keys_id'), table_name='keys', schema='esign')
    op.drop_table('keys', schema='esign')
    op.drop_index(op.f('ix_esign_users_id'), table_name='users', schema='esign')
    op.drop_index(op.f('ix_esign_users_email'), table_name='users', schema='esign')
    op.drop_table('users', schema='esign')
    # ### end Alembic commands ###
