"""invite changes

Revision ID: d3796dd75665
Revises: d732c7542a27
Create Date: 2026-01-13 10:55:37.858598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3796dd75665'
down_revision: Union[str, None] = 'd732c7542a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_invitations', sa.Column('message', sa.Text(), nullable=True), schema='esign')
    op.add_column('contract_invitations', sa.Column('responded_at', sa.TIMESTAMP(), nullable=True), schema='esign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_invitations', 'responded_at', schema='esign')
    op.drop_column('contract_invitations', 'message', schema='esign')
    # ### end Alembic commands ###
