"""init

Revision ID: d732c7542a27
Revises: 937cea7f4d41
Create Date: 2026-01-13 09:57:15.839453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd732c7542a27'
down_revision: Union[str, None] = '937cea7f4d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS esign")
    op.execute("CREATE SCHEMA IF NOT EXISTS api_management")
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_contracts_id'), 'contracts', ['id'], unique=False, schema='esign')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('encryption_salt', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_users_email'), 'users', ['email'], unique=True, schema='esign')
    op.create_index(op.f('ix_esign_users_id'), 'users', ['id'], unique=False, schema='esign')
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='api_management'
    )
    op.create_index(op.f('ix_api_management_api_keys_api_key'), 'api_keys', ['api_key'], unique=True, schema='api_management')
    op.create_index(op.f('ix_api_management_api_keys_id'), 'api_keys', ['id'], unique=False, schema='api_management')
    op.create_table('contract_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='invitationstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_contract_invitations_id'), 'contract_invitations', ['id'], unique=False, schema='esign')
    op.create_table('keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_keys_id'), 'keys', ['id'], unique=False, schema='esign')
    op.create_table('signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_signatures_id'), 'signatures', ['id'], unique=False, schema='esign')
    op.create_index(op.f('ix_esign_signatures_user_id'), 'signatures', ['user_id'], unique=False, schema='esign')
    op.create_table('api_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_management.api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='api_management'
    )
    op.create_index(op.f('ix_api_management_api_logs_api_key_id'), 'api_logs', ['api_key_id'], unique=False, schema='api_management')
    op.create_index(op.f('ix_api_management_api_logs_id'), 'api_logs', ['id'], unique=False, schema='api_management')
    op.create_table('api_usage_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year_week', sa.String(), nullable=False),
    sa.Column('year_month', sa.String(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('cumulative_calls', sa.Integer(), nullable=False),
    sa.Column('usage_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_management.api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='api_management'
    )
    op.create_index(op.f('ix_api_management_api_usage_summary_api_key_id'), 'api_usage_summary', ['api_key_id'], unique=False, schema='api_management')
    op.create_index(op.f('ix_api_management_api_usage_summary_date'), 'api_usage_summary', ['date'], unique=False, schema='api_management')
    op.create_index(op.f('ix_api_management_api_usage_summary_id'), 'api_usage_summary', ['id'], unique=False, schema='api_management')
    op.create_index(op.f('ix_api_management_api_usage_summary_total_calls'), 'api_usage_summary', ['total_calls'], unique=False, schema='api_management')
    op.create_index(op.f('ix_api_management_api_usage_summary_year_month'), 'api_usage_summary', ['year_month'], unique=False, schema='api_management')
    op.create_index(op.f('ix_api_management_api_usage_summary_year_week'), 'api_usage_summary', ['year_week'], unique=False, schema='api_management')
    op.create_table('contract_parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signature_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['esign.contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signature_id'], ['esign.signatures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['esign.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='esign'
    )
    op.create_index(op.f('ix_esign_contract_parties_id'), 'contract_parties', ['id'], unique=False, schema='esign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SCHEMA IF EXISTS api_management CASCADE")
    op.execute("DROP SCHEMA IF EXISTS esign CASCADE")
    op.drop_index(op.f('ix_esign_contract_parties_id'), table_name='contract_parties', schema='esign')
    op.drop_table('contract_parties', schema='esign')
    op.drop_index(op.f('ix_api_management_api_usage_summary_year_week'), table_name='api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_usage_summary_year_month'), table_name='api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_usage_summary_total_calls'), table_name='api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_usage_summary_id'), table_name='api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_usage_summary_date'), table_name='api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_usage_summary_api_key_id'), table_name='api_usage_summary', schema='api_management')
    op.drop_table('api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_logs_id'), table_name='api_logs', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_logs_api_key_id'), table_name='api_logs', schema='api_management')
    op.drop_table('api_logs', schema='api_management')
    op.drop_index(op.f('ix_esign_signatures_user_id'), table_name='signatures', schema='esign')
    op.drop_index(op.f('ix_esign_signatures_id'), table_name='signatures', schema='esign')
    op.drop_table('signatures', schema='esign')
    op.drop_index(op.f('ix_esign_keys_id'), table_name='keys', schema='esign')
    op.drop_table('keys', schema='esign')
    op.drop_index(op.f('ix_esign_contract_invitations_id'), table_name='contract_invitations', schema='esign')
    op.drop_table('contract_invitations', schema='esign')
    op.drop_index(op.f('ix_api_management_api_keys_id'), table_name='api_keys', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_keys_api_key'), table_name='api_keys', schema='api_management')
    op.drop_table('api_keys', schema='api_management')
    op.drop_index(op.f('ix_esign_users_id'), table_name='users', schema='esign')
    op.drop_index(op.f('ix_esign_users_email'), table_name='users', schema='esign')
    op.drop_table('users', schema='esign')
    op.drop_index(op.f('ix_esign_contracts_id'), table_name='contracts', schema='esign')
    op.drop_table('contracts', schema='esign')
    # ### end Alembic commands ###
