"""Hashed Password Key

Revision ID: dea18c0f6c17
Revises: 7e1e52462bfe
Create Date: 2025-03-05 12:22:31.408267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea18c0f6c17'
down_revision: Union[str, None] = '7e1e52462bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encryption_key_hash', sa.String(), nullable=True), schema='esign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encryption_key_hash', schema='esign')
    # ### end Alembic commands ###
