"""Add API logging tables

Revision ID: f002c4d51ad9
Revises: 78ebf290641f
Create Date: 2025-03-04 15:16:01.185014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f002c4d51ad9'
down_revision: Union[str, None] = '78ebf290641f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keys', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True), schema='esign')
    op.alter_column('keys', 'public_key',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False,
               schema='esign')
    op.alter_column('keys', 'private_key',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False,
               schema='esign')
    op.add_column('signatures', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True), schema='esign')
    op.alter_column('signatures', 'filename',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False,
               schema='esign')
    op.alter_column('signatures', 'signature',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False,
               schema='esign')
    op.create_index(op.f('ix_esign_signatures_user_id'), 'signatures', ['user_id'], unique=False, schema='esign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esign_signatures_user_id'), table_name='signatures', schema='esign')
    op.alter_column('signatures', 'signature',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='esign')
    op.alter_column('signatures', 'filename',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='esign')
    op.drop_column('signatures', 'created_at', schema='esign')
    op.alter_column('keys', 'private_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='esign')
    op.alter_column('keys', 'public_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='esign')
    op.drop_column('keys', 'created_at', schema='esign')
    # ### end Alembic commands ###
