"""api user

Revision ID: f93cddcef388
Revises: f002c4d51ad9
Create Date: 2025-03-04 18:25:08.977315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93cddcef388'
down_revision: Union[str, None] = 'f002c4d51ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('is_active', sa.Boolean(), nullable=True), schema='api_management')
    op.alter_column('api_keys', 'api_key',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False,
               schema='api_management')
    op.add_column('api_logs', sa.Column('status_code', sa.Integer(), nullable=False), schema='api_management')
    op.create_index(op.f('ix_api_management_api_logs_api_key_id'), 'api_logs', ['api_key_id'], unique=False, schema='api_management')
    op.add_column('api_usage_summary', sa.Column('cumulative_calls', sa.Integer(), nullable=False), schema='api_management')
    op.create_index(op.f('ix_api_management_api_usage_summary_api_key_id'), 'api_usage_summary', ['api_key_id'], unique=False, schema='api_management')
    op.create_index(op.f('ix_api_management_api_usage_summary_total_calls'), 'api_usage_summary', ['total_calls'], unique=False, schema='api_management')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_management_api_usage_summary_total_calls'), table_name='api_usage_summary', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_usage_summary_api_key_id'), table_name='api_usage_summary', schema='api_management')
    op.drop_column('api_usage_summary', 'cumulative_calls', schema='api_management')
    op.drop_index(op.f('ix_api_management_api_logs_api_key_id'), table_name='api_logs', schema='api_management')
    op.drop_column('api_logs', 'status_code', schema='api_management')
    op.alter_column('api_keys', 'api_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='api_management')
    op.drop_column('api_keys', 'is_active', schema='api_management')
    # ### end Alembic commands ###
